Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2021-04, with the labels that each got.

#180 Update documentation with instructions for developers create individual obs_data tar files
  doc/sphinx/dev_checklist.rst
Labels: documentation

#177 Update user-facing documentation
  .gitignore
  doc/_static/MDTF_getting_started.pdf
  doc/_static/MDTF_walkthrough.pdf
  doc/copy_external_docs.py
  doc/docutils.conf
  doc/index.rst
  doc/sphinx/dev_start.rst
  doc/sphinx/dev_walkthrough.rst
  doc/sphinx/ref_cli.rst
  doc/sphinx/ref_data.rst
  doc/sphinx/ref_data_sources.rst
  doc/sphinx/ref_dev_toc.rst
  doc/sphinx/ref_runtime_mgrs.rst
  doc/sphinx/ref_toc.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
  doc/sphinx/start_nonconda.rst
  doc/sphinx_sites/NOAA_GFDL.rst
  sites/NOAA_GFDL/cli_gfdl.jsonc
  sites/NOAA_GFDL/cli_plugins.jsonc
  sites/NOAA_GFDL/doc/NOAA_GFDL.rst
  sites/local/README_sites.md
  sites/local/doc/local.rst
  src/cli.py
  src/cli_plugins.jsonc
  src/cli_template.jsonc
  src/tests/test_cli.py
Labels: documentation, framework

#166 Always use mamba for conda env installs
  .travis.yml
  src/conda/conda_env_setup.sh
Labels: framework

#185 Check vars for time dimension
  src/data_manager.py
  src/data_model.py
Labels: framework
