Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2021-07, with the labels that each got.

#249 Add pytest to _env_synthetic_data.yml
  src/conda/_env_synthetic_data.yml
Labels: framework

#246 Add support for convective_transition_diag POD and mdtf_test_data unit tests to GitHub actions workflow
  .github/workflows/mdtf_tests.yml
  src/conda/_env_synthetic_data.yml
  tests/github_actions_test_macos_set1.jsonc
  tests/github_actions_test_ubuntu_set1.jsonc
Labels: testing-CI

#251 Pull synthetic data package from PyPi
  .github/workflows/mdtf_tests.yml
Labels: framework, testing-CI

#161 Implement workarounds for model data with missing metadata
  data/fieldlist_GFDL.jsonc
  doc/sphinx/ref_cli.rst
  doc/sphinx/ref_conventions.rst
  doc/sphinx/ref_data.rst
  doc/sphinx/ref_data_sources.rst
  doc/sphinx/ref_toc.rst
  mdtf_framework.py
  setup.py
  sites/NOAA_GFDL/cli_gfdl.jsonc
  sites/NOAA_GFDL/gfdl.py
  sites/NOAA_GFDL/gfdl_util.py
  src/cli.py
  src/cli_plugins.jsonc
  src/cli_template.jsonc
  src/cmip6.py
  src/core.py
  src/data_manager.py
  src/data_model.py
  src/data_sources.py
  src/diagnostic.py
  src/environment_manager.py
  src/html/mdtf_footer.html
  src/html/mdtf_header.html
  src/html/pod_error_snippet.html
  src/html/pod_missing_snippet.html
  src/html/pod_result_snippet.html
  src/html/warning_snippet.html
  src/logging.jsonc
  src/output_manager.py
  src/preprocessor.py
  src/tests/shared_test_utils.py
  src/tests/test_core.py
  src/tests/test_data_manager.py
  src/tests/test_diagnostic.py
  src/tests/test_environment_manager.py
  src/tests/test_mdtf.py
  src/tests/test_units.py
  src/units.py
  src/util/__init__.py
  src/util/basic.py
  src/util/dataclass.py
  src/util/datelabel.py
  src/util/exceptions.py
  src/util/filesystem.py
  src/util/logs.py
  src/util/processes.py
  src/util/tests/test_filesystem.py
  src/verify_links.py
  src/xr_parser.py
Labels: framework
