Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2022-10, with the labels that each got.

#373 Feature/stc eddy heat fluxes
  diagnostics/stc_eddy_heat_fluxes/doc/stc_eddy_heat_fluxes.rst
  diagnostics/stc_eddy_heat_fluxes/make_era5-rean_pod-data.py
  diagnostics/stc_eddy_heat_fluxes/settings.jsonc
  diagnostics/stc_eddy_heat_fluxes/stc_eddy_heat_fluxes.html
  diagnostics/stc_eddy_heat_fluxes/stc_eddy_heat_fluxes.py
Labels: diagnostic

#409 Add stc eddy heat fluxes POD to CI
  .github/workflows/mdtf_tests.yml
  tests/github_actions_test_macos_set3.jsonc
  tests/github_actions_test_ubuntu_set3.jsonc
Labels: testing-CI

#410 bump package versions in doc requirements and env_dev yaml file
  doc/requirements.txt
  src/conda/env_dev.yml
Labels: bug, documentation

#411 Add static docs
  doc/_static/MDTF_getting_started.pdf
  doc/_static/MDTF_walkthrough.pdf
  doc/conf.py
  src/conda/env_dev.yml
Labels: documentation

#412 bump xarray version to 0.20 or later in python3 base yaml
  src/conda/env_python3_base.yml
Labels: framework

#407 Add multirun support: framework mods and example_multicase POD
  README.md
  diagnostics/example_multicase/case_config_example.yml
  diagnostics/example_multicase/case_info.yaml
  diagnostics/example_multicase/doc/example_multicase.rst
  diagnostics/example_multicase/example_multicase.html
  diagnostics/example_multicase/example_multicase.py
  diagnostics/example_multicase/multirun_config_template.jsonc
  diagnostics/example_multicase/settings.jsonc
  diagnostics/mixed_layer_depth/mixed_layer_depth.py
  diagnostics/ocn_surf_flux_diag/doc/ocn_surf_flux_diag.rst
  diagnostics/tropical_pacific_sea_level/doc/tropical_pacific_sea_level.rst
  doc/sphinx/dev_start.rst
  doc/sphinx/ref_cli.rst
  doc/sphinx/ref_runtime_mgrs.rst
  sites/NOAA_GFDL/CM4_proto_diag_table.txt
  sites/NOAA_GFDL/doc/NOAA_GFDL.rst
  sites/NOAA_GFDL/gfdl.py
  sites/NOAA_GFDL/mdtf_gfdl.csh
  src/cli.py
  src/cli_plugins.jsonc
  src/cli_template.jsonc
  src/conda/_env_synthetic_data.yml
  src/conda/env_base.yml
  src/conda/env_python3_base.yml
  src/core.py
  src/data_manager.py
  src/data_sources.py
  src/diagnostic.py
  src/environment_manager.py
  src/multirun.py
  src/output_manager.py
  src/pod_setup.py
  src/preprocessor.py
  src/query_fetch_preprocess.py
  src/util/basic.py
  src/util/filesystem.py
  src/xr_parser.py
Labels: feature-request, framework

#416 debug the albedofb POD
  .github/workflows/mdtf_tests.yml
  diagnostics/albedofb/albedofb.py
  diagnostics/albedofb/albedofb_calcs.py
  diagnostics/albedofb/doc/surface_albedo_feedback.rst
  diagnostics/albedofb/settings.jsonc
Labels: bug, diagnostic

#420 bump cartopy to v 0.21.0 to try and resolve issues with naturalearth
  diagnostics/temp_extremes_distshape/TempExtDistShape_CircComps_util.py
  src/conda/env_python3_base.yml
Labels: bug
