Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2022-05, with the labels that each got.

#279 Feature/blocking neale
  data/fieldlist_NCAR.jsonc
  diagnostics/blocking_neale/blocking.ncl
  diagnostics/blocking_neale/blocking_digested.ncl
  diagnostics/blocking_neale/blocking_funcs.ncl
  diagnostics/blocking_neale/blocking_neale.html
  diagnostics/blocking_neale/blocking_neale.py
  diagnostics/blocking_neale/doc/blocking_neale.rst
  diagnostics/blocking_neale/doc/figure_anncycle.CAM5.png
  diagnostics/blocking_neale/doc/figure_anncycle.OBS.png
  diagnostics/blocking_neale/doc/figure_freq_season.png
  diagnostics/blocking_neale/doc/gaussians.jpg
  diagnostics/blocking_neale/settings.jsonc
  diagnostics/blocking_neale/test/README
  diagnostics/blocking_neale/test/blocking.csh
  diagnostics/blocking_neale/test/test.ncl
  src/install.py
Labels: diagnostic

#333 Changed argument handling of mdtf_framework.py
  mdtf_framework.py
Labels: framework

#336 Support for preferred GFDL frepp components
  sites/NOAA_GFDL/gfdl.py
  src/data_manager.py
  src/data_model.py
Labels: framework, site-specific

#347 Remove OM4labs and dependencies from MDTF base yaml
  src/conda/env_base.yml
  src/conda/env_python3_base.yml
Labels: framework

#344 Debug stc eddy heat fluxes
  data/fieldlist_CMIP.jsonc
  src/core.py
Labels: bug, framework

#348 Merge develop updates into main branch
  data/fieldlist_CMIP.jsonc
  src/conda/env_base.yml
  src/conda/env_python3_base.yml
  src/core.py
Labels: framework

#353 change required python version to 3.7 in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  doc/sphinx/dev_start.rst
Labels: docs-policy

#356 define _tags kwarg as an 'extra' kwarg
  src/core.py
Labels: bug, framework

#355 Add intake-xarray to env_python3_base.yml
  src/conda/env_python3_base.yml
Labels: feature-request, framework

#358 Merge python3_base yaml update into main
  src/conda/env_python3_base.yml
Labels: feature-request, framework
