Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2022-09, with the labels that each got.

#399 Pod/albedofb
  diagnostics/albedofb/albedofb.html
  diagnostics/albedofb/albedofb.py
  diagnostics/albedofb/albedofb_calcs.py
  diagnostics/albedofb/doc/surface_albedo_feedback.rst
  diagnostics/albedofb/my_tests.jsonc
  diagnostics/albedofb/settings.jsonc
Labels: diagnostic

#406 update cartopy version in python3 conda environment file
  src/conda/env_python3_base.yml
Labels: bug, framework

#408 add cython to env_python3_base.yml
  src/conda/env_python3_base.yml
Labels: framework
