Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2022-06, with the labels that each got.

#351 Frepp wrapper for MDTF
  sites/NOAA_GFDL/mdtf_frepp_template.jsonc
  sites/NOAA_GFDL/mdtf_gfdl.csh
Labels: bug, framework, site-specific

#369 Add PODs to the readme.md file
  README.md
Labels: documentation

#377 Update CM4_proto_diag_table.txt
  sites/NOAA_GFDL/CM4_proto_diag_table.txt
Labels: site-specific

#372 Commit existing framework internal documentation (#6)
  diagnostics/ENSO_MSE/doc/ENSO_MSE.rst
  diagnostics/ENSO_MSE/doc/README_LEVEL_01.rst
  diagnostics/ENSO_MSE/doc/README_LEVEL_02.rst
  diagnostics/ENSO_MSE/doc/README_LEVEL_03.rst
  diagnostics/ENSO_MSE/doc/README_LEVEL_04.rst
  diagnostics/ENSO_MSE/doc/README_general.rst
  diagnostics/ENSO_RWS/doc/ENSO_RWS.rst
  diagnostics/MJO_suite/doc/MJO_suite.rst
  diagnostics/blocking_neale/doc/blocking_neale.rst
  diagnostics/ocn_surf_flux_diag/doc/ocn_surf_flux_diag.rst
  diagnostics/precip_buoy_diag/doc/precip_buoy_diag.rst
  diagnostics/tropical_pacific_sea_level/doc/tropical_pacific_sea_level.rst
  doc/_static/MDTF_getting_started.pdf
  doc/_static/MDTF_walkthrough.pdf
  doc/_static/custom.css
  doc/conf.py
  doc/sphinx/fmwk_autodoc_toc.rst
  doc/sphinx/fmwk_datamodel.rst
  doc/sphinx/fmwk_doc_toc.rst
  doc/sphinx/fmwk_extend.rst
  doc/sphinx/fmwk_intro.rst
  doc/sphinx/fmwk_obj_hierarchy.rst
  doc/sphinx/fmwk_plugins.rst
  doc/sphinx/fmwk_preprocess.rst
  doc/sphinx/fmwk_provenance.rst
  doc/sphinx/fmwk_toc.rst
  doc/sphinx/fmwk_utils.rst
  doc/sphinx/start_install.rst
  setup.py
  src/cli.py
  src/cmip6.py
  src/data_model.py
  src/environment_manager.py
  src/output_manager.py
  src/preprocessor.py
  src/xr_parser.py
Labels: documentation

#379 Update docs
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  doc/sphinx/dev_checklist.rst
  doc/sphinx/dev_git_intro.rst
  doc/sphinx/dev_start.rst
  doc/sphinx/start_install.rst
  src/default_tests.jsonc
Labels: documentation

#380 Toggle control of coordinate renaming via `rename_coords` attribute
  src/data_manager.py
  src/data_model.py
  src/diagnostic.py
  src/preprocessor.py
Labels: framework

#384 add nc-time-axis to python3 yaml
  src/conda/env_python3_base.yml
Labels: framework

#385 Fix for preferred component functionality
  sites/NOAA_GFDL/gfdl.py
Labels: bug, framework

#387 Fix for undefined associated_files attribute
  src/data_manager.py
Labels: bug, site-specific
