Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2023-08, with the labels that each got.

#473 stop the macos tests in the ci
  .github/workflows/mdtf_tests.yml
Labels: bug

#475 Update esm intake version
  src/conda/env_base.yml
  src/conda/env_dev.yml
Labels: bug

#472 Add multirun capability to blocking_neale POD
  diagnostics/blocking_neale/blocking.ncl
  diagnostics/blocking_neale/blocking_digested.ncl
  diagnostics/blocking_neale/blocking_funcs.ncl
  diagnostics/blocking_neale/blocking_neale.html
  diagnostics/blocking_neale/blocking_neale.py
  diagnostics/blocking_neale/doc/blocking_neale.rst
  diagnostics/blocking_neale/settings.jsonc
  src/core.py
  src/diagnostic.py
  src/environment_manager.py
  src/output_manager.py
  src/preprocessor.py
Labels: diagnostic

#479 Feature/stc spv extremes
  diagnostics/stc_spv_extremes/doc/make_era5-rean_pod-data.py
  diagnostics/stc_spv_extremes/doc/stc_spv_extremes.rst
  diagnostics/stc_spv_extremes/settings.jsonc
  diagnostics/stc_spv_extremes/stc_spv_extremes.html
  diagnostics/stc_spv_extremes/stc_spv_extremes.py
  diagnostics/stc_spv_extremes/stc_spv_extremes_defs.py
Labels: framework

#481 FIx conda issues in GitHub Actions
  .github/workflows/mdtf_tests.yml
  tests/github_actions_test_macos_set1.jsonc
  tests/github_actions_test_macos_set2.jsonc
  tests/github_actions_test_macos_set3.jsonc
  tests/github_actions_test_ubuntu_set1.jsonc
  tests/github_actions_test_ubuntu_set2.jsonc
  tests/github_actions_test_ubuntu_set3.jsonc
Labels: bug, testing-CI
