Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-08, with the labels that each got.

#650 add logic to throw out elements out of date_range in check_group_date…
  src/preprocessor.py
Labels: framework, data catalogs

#651 Fix cat templates
  src/preprocessor.py
  src/util/catalog.py
  tools/catalog_builder/catalog_builder.py
Labels: framework, data catalogs

#652 no more time_range in groupby_attrs templates
  diagnostics/example_multicase/esm_catalog_CMIP_synthetic_r1i1p1f1_gr1.json
  src/util/catalog.py
  tools/catalog_builder/catalog_builder.py
Labels: framework, data catalogs

#654 catalog builder updates
  src/conda/env_base.yml
  src/conda/env_base_micromamba.yml
  tools/catalog_builder/catalog_builder.py
Labels: tool, data catalogs

#653 Update ci
  .github/workflows/mdtf_tests.yml
  data/fieldlist_CESM.jsonc
  doc/sphinx/ref_catalogs.rst
  doc/sphinx/ref_toc.rst
  doc/sphinx/start_config.rst
  src/preprocessor.py
  src/util/datelabel.py
  tests/esm_catalog_CESM_test_macos.json
  tests/esm_catalog_CMIP_test_macos.json
  tests/esm_catalog_GFDL_test_macos.json
  tests/esm_catalog_GFDL_test_ubuntu.json
  tests/esm_catalog_test_macos.csv
  tests/esm_catalog_test_macos.json
  tests/esm_catalog_test_ubuntu.csv
  tests/esm_catalog_test_ubuntu.json
  tests/github_actions_test_macos_set1.jsonc
  tests/github_actions_test_macos_set2.jsonc
  tests/github_actions_test_macos_set3.jsonc
  tests/github_actions_test_ubuntu_set1.jsonc
  tests/github_actions_test_ubuntu_set2.jsonc
  tests/github_actions_test_ubuntu_set3.jsonc
Labels: testing-CI, documentation

#655 delete confusing attributes
  src/preprocessor.py
Labels: framework

#656 fix time and time_range entries in test csv files
  tests/esm_catalog_test_macos.csv
  tests/esm_catalog_test_ubuntu.csv
Labels: testing-CI

#657 add date to drop_vars
  src/preprocessor.py
Labels: framework

#658 fix variable typo in reconcile_names
  src/xr_parser.py
Labels: bug, framework

#661 add logic to handle unexpected type in check_group_daterange
  src/preprocessor.py
Labels: framework

#663 add function to verify that conda dirs exists after parsing config file
  mdtf_framework.py
  src/cli.py
Labels: framework

#665 change time sort in preprocessor to rely on time coord
  src/preprocessor.py
Labels: framework

#668 add falwa package to python3 base env files
  src/conda/env_python3_base.yml
  src/conda/env_python3_base_micromamba.yml
Labels: Conda/micromamba

#670 Update docs
  doc/sphinx/dev_git_intro.rst
  doc/sphinx/dev_start.rst
  doc/sphinx/ref_catalogs.rst
  doc/sphinx/ref_output.rst
  doc/sphinx/ref_submodules.rst
  doc/sphinx/start_install.rst
  doc/sphinx/start_multirun.rst
Labels: documentation

#669 rework check_group_daterange to work with data starting at year 0001
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#673 Clean up docstrings
  src/cmip6.py
  src/data_model.py
  src/environment_manager.py
  src/preprocessor.py
  src/translation.py
  src/util/basic.py
  src/util/dataclass.py
  src/util/filesystem.py
  src/util/logs.py
  src/verify_links.py
Labels: framework

#674 initial implementation of notebook PODs
  diagnostics/example_notebook/Test_Notebook.ipynb
  diagnostics/example_notebook/doc/example_notebook.rst
  diagnostics/example_notebook/example_notebook.html
  diagnostics/example_notebook/example_notebook.ipynb
  diagnostics/example_notebook/settings.jsonc
  src/environment_manager.py
  src/pod_setup.py
Labels: diagnostic, framework

#675 Ci fixes
  src/preprocessor.py
  src/util/dataclass.py
  src/util/datelabel.py
  src/xr_parser.py
Labels: framework, testing-CI
