Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-05, with the labels that each got.

#557 addng gfdl cmip var mapping plus the additonal info needed. note that…
  data/gfdl-cmor-tables/gfdl_to_cmip5_vars.csv
  data/gfdl-cmor-tables/gfdl_to_cmip6_vars.csv
  data/gfdl-cmor-tables/pandas_usage.py
Labels: data

#561 Refactor translator
  data/fieldlist_CESM.jsonc
  data/fieldlist_CMIP.jsonc
  data/fieldlist_GFDL.jsonc
  src/data_model.py
  src/data_sources.py
  src/pod_setup.py
  src/preprocessor.py
  src/translation.py
  src/units.py
  src/util/catalog.py
  src/varlist_util.py
Labels: framework, data, fieldlist

#563 fix catalog builder src module imports
  tools/__init__.py
  tools/catalog_builder/__init__.py
  tools/catalog_builder/catalog_builder.py
Labels: bug, tool

#564 add logic to format method of DateFrequency object
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#565 Fix issues with preprocessor functions
  src/data_model.py
  src/data_sources.py
  src/preprocessor.py
  src/translation.py
  src/varlist_util.py
Labels: framework

#568 fix check_group_daterange function in preprocessor.py
  src/preprocessor.py
Labels: framework

#569 update imports in preprocessor.py
  src/preprocessor.py
Labels: framework

#570 More pr stuff
  src/data_model.py
  src/preprocessor.py
Labels: framework

#571 More pp fixes
  src/data_model.py
  src/preprocessor.py
  src/translation.py
Labels: framework

#572 fix pp query logic
  src/preprocessor.py
  src/translation.py
  src/xr_parser.py
Labels: framework

#575 Fix issues with coordiante is_scalar attribute
  src/data_model.py
  src/preprocessor.py
  src/translation.py
Labels: framework

#576 reattch calendar attr after xr.decode_cf()
  src/xr_parser.py
Labels: framework

#577 remove | operator from query_catalog
  src/preprocessor.py
Labels: framework

#578 add packages required by faw diag to python3 base yaml
  src/conda/env_python3_base.yml
Labels: Conda/micromamba

#579 grab attrs from ds.time.encoding instead of reattaching
  src/preprocessor.py
  src/xr_parser.py
Labels: framework

#580 fix issues with check_group_daterange
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#581 add logic to check_metadata to search in ds_var.encoding
  src/xr_parser.py
Labels: framework
