Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-09, with the labels that each got.

#679 Iss 677
  data/fieldlist_GFDL.jsonc
  src/preprocessor.py
  src/xr_parser.py
Labels: bug, framework

#680 add check for correct config file path to framework driver
  mdtf_framework.py
Labels: framework

#683 move global realm setting to pod data section
  diagnostics/SM_ET_coupling/settings.jsonc
  diagnostics/forcing_feedback/settings.jsonc
  diagnostics/stc_eddy_heat_fluxes/settings.jsonc
  diagnostics/stc_qbo_enso/settings.jsonc
  diagnostics/stc_spv_extremes/settings.jsonc
  diagnostics/top_heaviness_metric/settings.jsonc
  doc/sphinx/pod_settings.rst
  src/varlist_util.py
Labels: bug, framework

#685 add static variable support to preprocessor
  src/preprocessor.py
Labels: bug, framework

#678 Container
  .github/workflows/docker-build-and-push.yml
  Dockerfile
Labels: feature-request, containers

#687 Container Documentation
  diagnostics/example_multicase/container_cat.csv
  diagnostics/example_multicase/container_cat.json
  diagnostics/example_multicase/container_config_demo.jsonc
  doc/sphinx/dev_start.rst
  doc/sphinx/ref_container.rst
  doc/sphinx/ref_toc.rst
Labels: documentation, containers

#688 Fix ci bugs
  .github/workflows/mdtf_tests.yml
  data/fieldlist_GFDL.jsonc
  diagnostics/stc_eddy_heat_fluxes/settings.jsonc
  src/pod_setup.py
  src/preprocessor.py
  src/translation.py
  src/units.py
  src/util/datelabel.py
  src/xr_parser.py
  tests/esm_catalog_test_macos.csv
  tests/esm_catalog_test_ubuntu.csv
  tests/github_actions_test_macos_1a.jsonc
  tests/github_actions_test_macos_1b.jsonc
  tests/github_actions_test_macos_2.jsonc
  tests/github_actions_test_macos_3.jsonc
  tests/github_actions_test_ubuntu_1a.jsonc
  tests/github_actions_test_ubuntu_1b.jsonc
  tests/github_actions_test_ubuntu_2.jsonc
  tests/github_actions_test_ubuntu_3.jsonc
Labels: bug, framework

#691 infer 'start_time' and 'end_time' from 'time_range' due to type issues
  src/preprocessor.py
Labels: framework

#693 move line setting date_range in query_catalog()
  src/preprocessor.py
Labels: bug, framework

#692 Fix issues in pp query
  src/preprocessor.py
  src/xr_parser.py
Labels: framework
