Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-12, with the labels that each got.

#717 Fix dummy translation method in NoTranslationFieldlist
  doc/sphinx/start_config.rst
  src/pod_setup.py
  src/preprocessor.py
  src/translation.py
Labels: bug, framework

#718 Reimplement crop date range capability
  src/preprocessor.py
  src/util/catalog.py
  src/util/datelabel.py
Labels: framework

#720 Create drop attributes func
  src/conda/env_dev.yml
  src/preprocessor.py
Labels: framework

#722 Update mdtf dev env file
  src/conda/env_dev.yml
Labels: Conda/micromamba

#721 Fix various pp issues related to running seaice_suite
  data/fieldlist_GFDL.jsonc
  diagnostics/seaice_suite/seaice_suite_sic_mean_sigma.py
  src/data_sources.py
  src/preprocessor.py
  src/units.py
  src/xr_parser.py
Labels: bug, framework

#725 fix typo in container_config_demo.jsonc
  diagnostics/example_multicase/container_config_demo.jsonc
Labels: containers

#726 Cesm cat builder
  data/fieldlist_CESM.jsonc
  data/fieldlist_GFDL.jsonc
  tools/catalog_builder/catalog_builder.py
  tools/catalog_builder/parsers.py
Labels: data catalogs
