Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-04, with the labels that each got.

#524 Fixes for cesm catalog builder and MJO_suite settings file
  diagnostics/MJO_suite/settings.jsonc
  src/pod_setup.py
  tools/catalog_builder/catalog_builder.py
Labels: tool

#530 fix bug in module_config.yml
  templates/module_config.yml
Labels: bug

#533 More doc updates
  .github/workflows/sphinx_action.yml
  diagnostics/TC_Rain/doc/TC_Rain.rst
  diagnostics/albedofb/doc/surface_albedo_feedback.rst
  diagnostics/example_multicase/doc/example_multicase.rst
  diagnostics/stc_eddy_heat_fluxes/doc/stc_eddy_heat_fluxes.rst
  diagnostics/stc_ozone/doc/stc_ozone.rst
  diagnostics/stc_qbo_enso/doc/stc_qbo_enso.rst
  diagnostics/stc_spv_extremes/doc/stc_spv_extremes.rst
  diagnostics/stc_vert_wave_coupling/doc/stc_vert_wave_coupling.rst
  diagnostics/top_heaviness_metric/doc/top_heaviness_metric.rst
  doc/conf.py
  doc/copy_external_docs.py
  doc/sphinx/dev_cheatsheet.rst
  doc/sphinx/dev_coding_tips.rst
  doc/sphinx/dev_guidelines.rst
  doc/sphinx/fmwk_preprocess.rst
  doc/sphinx/pod_requirements.rst
  doc/sphinx/pod_settings.rst
  doc/sphinx/ref_cli.rst
  doc/sphinx/ref_conventions.rst
  doc/sphinx/ref_data.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
  doc/sphinx/start_multirun.rst
  doc/sphinx/start_overview.rst
  src/data_sources.py
  src/xr_parser.py
  tools/catalog_builder/doc/catalog_builder.rst
Labels: documentation

#534 More doc updates
  .github/workflows/sphinx_action.yml
  doc/copy_external_docs.py
  doc/requirements.txt
  doc/tex_all.rst
  src/cli.py
  src/preprocessor.py
  src/xr_parser.py
Labels: testing-CI, documentation

#535 More doc updates
  README.md
  doc/sphinx/dev_start.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
Labels: documentation

#537 add checks and default values for parameters that may be optionally s…
  src/output_manager.py
Labels: framework

#538 clean up environment_manager
  src/environment_manager.py
Labels: framework

#539 More fixes
  src/util/filesystem.py
Labels: framework

#540 Fix GFDL spec in catalog builder
  tools/catalog_builder/catalog_builder.py
Labels: tool

#542 Update docs
  doc/sphinx/dev_git_intro.rst
  doc/sphinx/dev_start.rst
  doc/sphinx/pod_settings.rst
  doc/sphinx/ref_envvars.rst
  doc/sphinx/ref_settings.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
Labels: documentation

#544 Am5 fixes
  data/fieldlist_GFDL.jsonc
  src/data_model.py
  src/preprocessor.py
  src/translation.py
  src/varlist_util.py
Labels: framework, fieldlist

#545 Fix gfdl parser in catalog builder
  tools/catalog_builder/catalog_builder.py
Labels: tool

#546 add start_time and end_time attrs to catalog_builder.py
  tools/catalog_builder/catalog_builder.py
Labels: tool

#547 Extend cat builder
  data/fieldlist_CMIP.jsonc
  data/fieldlist_GFDL.jsonc
  diagnostics/stc_ozone/settings.jsonc
  tools/catalog_builder/catalog_builder.py
  tools/catalog_builder/examples/templates/example_builder_config.yml
Labels: tool

#548 update cmip6 cmor tables
  data/cmip6-cmor-tables/Tables/CMIP6_CV.json
Labels: data

#550 529 contrib
  .all-contributorsrc
  README.md
Labels: docs-policy
