Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-03, with the labels that each got.

#515 add sphinx build action on pull request
  .github/workflows/sphinx_action.yml
  doc/index.rst
  doc/sphinx/dev_cheatsheet.rst
  doc/sphinx/dev_start.rst
Labels: testing-CI, docs-policy

#521 remove old conda envs if found on build
  src/conda/conda_env_setup.sh
Labels: Conda/micromamba

#522 fix logic in pp nc_var_encoding method
  src/preprocessor.py
Labels: bug, framework

#523 Refactor pp
  .github/workflows/sphinx_action.yml
  README.md
  doc/latexmkrc
  src/conda/conda_env_setup.sh
Labels: framework
