Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-07, with the labels that each got.

#600 add support for yyyy, yyyymm to start and end dates
  src/cli.py
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#602 add logic to check standard and long names to convertdataarray function
  src/preprocessor.py
  src/units.py
Labels: framework

#603 Fix issues inf EOF_500hpa POD
  diagnostics/EOF_500hPa/EOF_500hPa.py
  diagnostics/EOF_500hPa/compute_anomalies.ncl
  diagnostics/EOF_500hPa/eof_natlantic.ncl
  diagnostics/EOF_500hPa/eof_npacific.ncl
  diagnostics/EOF_500hPa/settings.jsonc
Labels: diagnostic

#604 Add alternate support
  src/preprocessor.py
  src/util/__init__.py
  src/util/basic.py
  src/varlist_util.py
  src/xr_parser.py
Labels: framework

#606 reimplement reconcile_variable and fix pathing issues in forcing_feeback
  diagnostics/forcing_feedback/forcing_feedback_plot.py
  diagnostics/forcing_feedback/forcing_feedback_util.py
  src/preprocessor.py
  src/xr_parser.py
Labels: diagnostic, framework

#608 Update README.md
  README.md
Labels: documentation

#610 remove redundant pip intall lines from env_python3_base.yml
  src/conda/env_python3_base.yml
Labels: Conda/micromamba

#611 add logic for query freq and make parsing in process more explicit
  src/preprocessor.py
Labels: framework

#613 add exception list of vars to prevent overwriting in preprocessor
  src/preprocessor.py
Labels: framework

#612 Fix xr parser issues
  src/preprocessor.py
  src/xr_parser.py
Labels: framework

#615 add frequency entry to top_heaviness_metric pod settings file
  diagnostics/top_heaviness_metric/settings.jsonc
Labels: diagnostic

#616 fix issues in environment_manager env_vars and pod logging
  src/environment_manager.py
  src/pod_setup.py
  src/util/logs.py
Labels: framework

#617 fix EOF500hPa issues
  diagnostics/EOF_500hPa/compute_anomalies.ncl
  src/util/path_utils.py
Labels: diagnostic, framework

#618 add logic to convert pod_env_vars to strings
  src/pod_setup.py
Labels: diagnostic, data

#619 Remove sites dir
  doc/sphinx/start_install.rst
  sites/NOAA_GFDL/CM4_proto_diag_table.txt
  sites/NOAA_GFDL/__init__.py
  sites/NOAA_GFDL/cli_gfdl.jsonc
  sites/NOAA_GFDL/cli_plugins.jsonc
  sites/NOAA_GFDL/cli_subcommands.jsonc
  sites/NOAA_GFDL/default_gfdl.jsonc
  sites/NOAA_GFDL/gfdl.py
  sites/NOAA_GFDL/gfdl_multirun.py
  sites/NOAA_GFDL/gfdl_multirun_config_template.jsonc
  sites/NOAA_GFDL/gfdl_util.py
  sites/NOAA_GFDL/mdtf_frepp_template.jsonc
  sites/NOAA_GFDL/mdtf_gfdl.csh
  sites/NOAA_GFDL/tests/__init__.py
  sites/NOAA_GFDL/tests/test_gfdl.py
  sites/__init__.py
Labels: framework

#620 move gfdl ref files
  data/CM4_proto_diag_table.txt
  templates/mdtf_gfdl.csh
Labels: site-specific

#622 fix forcing_feedback paths
  diagnostics/forcing_feedback/forcing_feedback_kernelcalcs.py
  diagnostics/forcing_feedback/forcing_feedback_plot.py
  diagnostics/forcing_feedback/forcing_feedback_util.py
Labels: diagnostic

#623 fix output_manager cleanup
  src/output_manager.py
Labels: bug, framework

#624 update path to check in compute_anomalies.ncl
  diagnostics/EOF_500hPa/compute_anomalies.ncl
Labels: diagnostic

#625 add call to remove model/PS files to cleanup_pod_files
  src/output_manager.py
Labels: diagnostic

#626 reimplement date range checks in catalog query
  src/preprocessor.py
Labels: framework

#628 add 'precipitation_flux' to CESM fieldlist
  data/fieldlist_CESM.jsonc
Labels: data

#629 Test nopp
  mdtf_framework.py
  src/environment_manager.py
  src/preprocessor.py
  src/util/__init__.py
  src/util/catalog.py
  src/util/datelabel.py
Labels: framework

#631 fix precipratetofluxconversion edit_request method
  src/preprocessor.py
Labels: framework

#632 fix multicase_dict pod attribute
  src/output_manager.py
  src/pod_setup.py
Labels: framework

#633 Implement mp
  mdtf_framework.py
Labels: framework

#634 Fix multi-pod implementation
  mdtf_framework.py
  src/data_model.py
  src/data_sources.py
  src/environment_manager.py
  src/pod_setup.py
  src/preprocessor.py
  src/util/path_utils.py
  src/varlist_util.py
Labels: framework

#635 fix alternates
  src/varlist_util.py
Labels: framework

#636 add logic to infer start and end times for time range and update form…
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#637 Fix pod multicase dict
  src/environment_manager.py
  src/output_manager.py
  src/pod_setup.py
  src/verify_links.py
Labels: framework

#639 Fix translator
  src/data_sources.py
  src/pod_setup.py
  src/preprocessor.py
  src/translation.py
  src/varlist_util.py
Labels: framework

#641 update conda envs to python 3.12
  .github/PULL_REQUEST_TEMPLATE.md
  doc/conf.py
  doc/sphinx/dev_guidelines.rst
  doc/sphinx/dev_start.rst
  setup.py
  src/conda/_env_synthetic_data.yml
  src/conda/env_NCL_base.yml
  src/conda/env_NCL_base_micromamba.yml
  src/conda/env_R_base.yml
  src/conda/env_base.yml
  src/conda/env_base_micromamba.yml
  src/conda/env_dev.yml
  src/conda/env_python3_base.yml
  src/conda/env_python3_base_micromamba.yml
Labels: Conda/micromamba

#642 Fix more issues
  src/data_model.py
  src/environment_manager.py
  src/output_manager.py
  src/pod_setup.py
  src/preprocessor.py
  src/translation.py
  src/util/basic.py
  src/varlist_util.py
  src/xr_parser.py
Labels: framework

#643 Fix stuff
  src/pod_setup.py
  src/util/basic.py
  src/util/datelabel.py
  src/util/exceptions.py
  src/util/json_utils.py
  src/util/logs.py
  src/util/processes.py
Labels: framework

#644 Fix html templates
  diagnostics/MJO_suite/MJO_suite.html
  diagnostics/example/example.html
  diagnostics/example_multicase/example_multicase.html
  src/html/mdtf_header.html
  src/html/mdtf_multirun_header.html
  src/html/multirun_pod_result_snippet.html
  src/html/pod_error_snippet.html
  src/html/pod_result_snippet.html
  src/output_manager.py
  src/util/filesystem.py
Labels: framework

#646 Fix pod paths and util formatting
  diagnostics/MJO_suite/mjo.ncl
  diagnostics/MJO_suite/mjo_spectra.ncl
  diagnostics/precip_diurnal_cycle/pr_diurnal_phase.ncl
  diagnostics/precip_diurnal_cycle/precip_diurnal_cycle.py
  src/util/datelabel.py
Labels: diagnostic, framework

#647 Add cat documentatation
  doc/sphinx/start_config.rst
Labels: documentation

#645 add documentation to serve as a reference to MDTF output
  doc/sphinx/ref_output.rst
  doc/sphinx/ref_toc.rst
Labels: documentation

#648 fix typo in ref_output.rst
  doc/sphinx/ref_output.rst
Labels: documentation

#649 Update docs
  diagnostics/example_multicase/example_multicase.py
  doc/sphinx/dev_cheatsheet.rst
  doc/sphinx/dev_coding_tips.rst
  doc/sphinx/dev_git_intro.rst
  doc/sphinx/dev_guidelines.rst
  doc/sphinx/fmwk_preprocess.rst
  doc/sphinx/pod_requirements.rst
  doc/sphinx/pod_settings.rst
  doc/sphinx/ref_cli.rst
  doc/sphinx/ref_data.rst
  doc/sphinx/ref_envvars.rst
  doc/sphinx/ref_output.rst
  doc/sphinx/ref_submodules.rst
Labels: documentation
