Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2024-06, with the labels that each got.

#583 Fix outstanding preprocessor issues
  src/preprocessor.py
Labels: framework

#584 fix to write single variable with POD's convention in write_dataset
  src/preprocessor.py
Labels: framework

#586 create function rename_dataset_vars and fix in catalog.py
  mdtf_framework.py
  src/preprocessor.py
  src/util/catalog.py
Labels: framework

#587 Refactor catalog write
  mdtf_framework.py
  src/data_sources.py
  src/preprocessor.py
  src/util/catalog.py
  src/util/filesystem.py
Labels: framework

#589 fix settings file for forcing_feedback
  diagnostics/forcing_feedback/settings.jsonc
Labels: diagnostic

#590 update mdtf output catalog columns
  src/preprocessor.py
  src/util/catalog.py
Labels: framework, data catalogs

#591 uncomment writing file terminal message
  src/preprocessor.py
Labels: framework

#592 Fix MJO suite env vars
  diagnostics/MJO_suite/MJO_suite.py
  diagnostics/MJO_suite/mjo.ncl
  diagnostics/MJO_suite/mjo_EOF.ncl
  diagnostics/MJO_suite/mjo_EOF_cal.ncl
  diagnostics/MJO_suite/mjo_lag_lat_lon.ncl
  diagnostics/MJO_suite/mjo_life_cycle.ncl
  diagnostics/MJO_suite/mjo_spectra.ncl
Labels: diagnostic

#593 Add support for string time_ranges and date ranges with multiple delimiters
  src/preprocessor.py
  src/util/datelabel.py
Labels: framework

#594 change file_dir variable and fix writing error in MJO_suite
  diagnostics/MJO_suite/daily_anom.ncl
  diagnostics/MJO_suite/daily_netcdf.ncl
  diagnostics/MJO_suite/mjo.ncl
  diagnostics/MJO_suite/mjo_EOF.ncl
  diagnostics/MJO_suite/mjo_EOF_cal.ncl
  diagnostics/MJO_suite/mjo_lag_lat_lon.ncl
  diagnostics/MJO_suite/mjo_life_cycle.ncl
  diagnostics/MJO_suite/mjo_spectra.ncl
Labels: diagnostic

#595 add var.log.info message for catalog query
  src/preprocessor.py
Labels: framework

#596 fix typo in query_catalog error msg
  src/preprocessor.py
Labels: framework

#597 add monthly date_format in check_group_daterange
  src/preprocessor.py
Labels: framework

#598 fix realm definition in varlistentry.from_struct
  src/varlist_util.py
Labels: framework
