Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2025-04, with the labels that each got.

#782 Integrate MAR notebooks
  data/fieldlist_GFDL.jsonc
  diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.html
  diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.ipynb
  diagnostics/mar/SST_bias_NOAA_OISSTv2/settings.jsonc
  src/data_sources.py
  src/environment_manager.py
  src/pod_setup.py
  src/preprocessor.py
  src/util/path_utils.py
Labels: feature-request, framework

#784 add run-MDTF [GFDL driver script]
  tools/run-MDTF/README.md
  tools/run-MDTF/config/pod_config.json
  tools/run-MDTF/config/template_config.jsonc
  tools/run-MDTF/run-MDTF.sh
  tools/run-MDTF/run-MDTF_frepp.csh
  tools/run-MDTF/scripts/gen_config.py
  tools/run-MDTF/scripts/gen_index.py
  tools/run-MDTF/scripts/index.html
  tools/run-MDTF/scripts/mdtf_diag_banner.png
Labels: tool

#790 Update docs
  doc/copy_external_docs.py
  doc/sphinx/dev_cheatsheet.rst
  doc/sphinx/dev_coding_tips.rst
  doc/sphinx/dev_git_intro.rst
  tools/run-MDTF/doc/README.md
Labels: documentation

#791 refine MDTF-run script
  data/fieldlist_CMIP.jsonc
  diagnostics/mar/SST_bias_NOAA_OISSTv2/SST_bias_NOAA_OISSTv2.ipynb
  diagnostics/mar/SST_bias_NOAA_OISSTv2/settings.jsonc
  src/conda/env_dev.yml
  src/conda/env_python3_base.yml
  src/conda/env_python3_base_micromamba.yml
  tools/run-MDTF/config/pod_config.json
  tools/run-MDTF/doc/README.md
  tools/run-MDTF/run-MDTF.sh
  tools/run-MDTF/run-MDTF_frepp.csh
  tools/run-MDTF/scripts/gen_config.py
Labels: site-specific, tool, data catalogs

#792 Update docs with GFDL role account instructions
  doc/sphinx/dev_gfdl.rst
  doc/sphinx/pod_dev_toc.rst
Labels: documentation
