Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2025-01, with the labels that each got.

#731 add external script into example_notebook
  diagnostics/example_notebook/example_notebook.ipynb
  diagnostics/example_notebook/script.py
Labels: tool

#729 small fix
  tools/catalog_builder/parsers.py
Labels: bug, tool, data catalogs

#732 add function to normalize all time coord units
  src/preprocessor.py
Labels: bug, framework, data

#734 add new --freq flag in mdtf-test-data to docs and tests
  .github/workflows/mdtf_tests.yml
  README.md
  doc/sphinx/ref_container.rst
  doc/sphinx/start_install.rst
  templates/module_config.jsonc
  templates/runtime_config.jsonc
Labels: testing-CI, documentation, tool

#735 remove wildcard from realm_regex def
  doc/sphinx/ref_cli.rst
  src/cli.py
  src/data_sources.py
  templates/module_config.jsonc
  templates/module_config.yml
  templates/runtime_config.jsonc
  templates/runtime_config.yml
Labels: framework, data catalogs

#736 Pull Request for the MDSL POD
  diagnostics/MDSL/Ancillary_Codes/pre-regrid_refs_1deg_global.ipynb
  diagnostics/MDSL/Ancillary_Codes/preprocess_obs.ipynb
  diagnostics/MDSL/MDSL.html
  diagnostics/MDSL/MDSL.py
  diagnostics/MDSL/doc/MDSL.rst
  diagnostics/MDSL/doc/MDSL_Schematic.png
  diagnostics/MDSL/doc/global_output.png
  diagnostics/MDSL/doc/gs_output.png
  diagnostics/MDSL/gfdl_grid_fx.py
  diagnostics/MDSL/nch.py
  diagnostics/MDSL/other_grid_fx.py
  diagnostics/MDSL/plot_fx.py
  diagnostics/MDSL/settings.jsonc
Labels: diagnostic

#740 add needed packages for MDSL POD to env_python3_base.yml
  src/conda/env_python3_base.yml
Labels: Conda/micromamba

#737 Update docs
  diagnostics/example_multicase/multirun_config_template.jsonc
  doc/sphinx/dev_guidelines.rst
  doc/sphinx/pod_requirements.rst
  doc/sphinx/ref_catalogs.rst
  doc/sphinx/ref_container.rst
  doc/sphinx/ref_conventions.rst
  doc/sphinx/ref_data.rst
  doc/sphinx/ref_envvars.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
  doc/sphinx/start_multirun.rst
  doc/sphinx/start_toc.rst
  templates/module_config.jsonc
  templates/runtime_config.jsonc
Labels: documentation

#741 change version to 4.2 in doc/conf.py and setup.py
  doc/conf.py
  setup.py
Labels: documentation

#742 Add mdsl POD to docs
  README.md
  doc/_static/MDTF_Variable_Lists.html
Labels: documentation
