Repository NOAA-GFDL/MDTF-diagnostics, pull requests merged in 2025-02, with the labels that each got.

#743 downgrade xesmf to 0.8.7 to avoid package conflicts with esmf and esmpy
  src/conda/env_python3_base.yml
Labels: Conda/micromamba

#744 update installation instructions
  doc/sphinx/start_install.rst
Labels: documentation, Conda/micromamba

#745 Update documentation with Globus links
  README.md
  doc/sphinx/pod_requirements.rst
  doc/sphinx/start_config.rst
  doc/sphinx/start_install.rst
Labels: documentation

#749 fix variable_id definition in postprocessor catalog
  src/preprocessor.py
Labels: bug

#750 Fix pp time defs
  src/data_sources.py
  src/environment_manager.py
  src/preprocessor.py
  src/xr_parser.py
Labels: bug

#751 add land area fraction to fieldlists
  data/fieldlist_CESM.jsonc
  data/fieldlist_CMIP.jsonc
  data/fieldlist_GFDL.jsonc
Labels: fieldlist

#752 define frequency using var.T instead of var.T.unit in set_query
  src/data_sources.py
Labels: bug
